name: Pipeline CI/CD - ACME

on:
  push:
    branches:
      - develop
      - release
    workflow_dispatch:

  pull_request:
    branches:
      - main

jobs:
  develop:
    if: github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/test.yaml

  release-test:
    if: github.ref == 'refs/heads/release'
    uses: ./.github/workflows/test.yaml

  release-build:
    if: github.ref == 'refs/heads/release'
    needs: release-test
    uses: ./.github/workflows/build.yaml

  release-deploy:
    needs: release-build
    environment: release
    runs-on: ubuntu-latest
    steps:
      - name: Deploy para o ambiente de release
        run: echo "Deploy realizado com sucesso para o ambiente de release!"

  notify-release:
    needs: [release-build]
    runs-on: ubuntu-latest
    steps:
      - name: Notificar Sucesso
        if: success()
        run: echo "Deploy realizado com sucesso para o ambiente ${{ github.ref }}!"

      - name: Notificar Falha
        if: failure()
        run: echo "Deploy falhou para o ambiente ${{ github.ref }}!"

      - name: Sempre Notificar
        if: always()
        run: echo "Pipeline finalizado para o ambiente ${{ github.ref }}."

  main-test:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/test.yaml

  main-build:
    if: github.ref == 'refs/heads/main'
    needs: main-test
    uses: ./.github/workflows/build.yaml

  main-deploy:
    needs: main-build
    environment: main
    runs-on: ubuntu-latest
    steps:
      - name: Deploy para o ambiente de produção
        run: echo "Deploy realizado com sucesso para o ambiente de produção!"

  notify-main:
    needs: [main-build]
    runs-on: ubuntu-latest
    steps:
      - name: Notificar Sucesso
        if: success()
        run: echo "Deploy realizado com sucesso para o ambiente ${{ github.ref }}!"

      - name: Notificar Falha
        if: failure()
        run: echo "Deploy falhou para o ambiente ${{ github.ref }}!"

      - name: Sempre Notificar
        if: always()
        run: echo "Pipeline finalizado para o ambiente ${{ github.ref }}."
