name: Pipeline CI/CD - ACME

on:
  push:
    branches:
      - main
      - develop
      - release

jobs:
  develop:
    if: github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/test.yaml

  release-test:
    if: github.ref == 'refs/heads/release'
    uses: ./.github/workflows/test.yaml

  release-build:
    if: github.ref == 'refs/heads/release'
    needs: release-test
    uses: ./.github/workflows/build.yaml

  # release-deploy:
  #   if: github.ref == 'refs/heads/release' && success()
  #   needs: release-build
  #   uses: ./.github/workflows/deploy.yaml
  #   with:
  #     environment: release

  main-test:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/test.yaml

  main-build:
    if: github.ref == 'refs/heads/main'
    needs: main-test
    uses: ./.github/workflows/build.yaml

  # main-deploy:
  #   if: github.ref == 'refs/heads/main' && success()
  #   needs: main-build
  #   uses: ./.github/workflows/deploy.yaml
  #   with:
  #     environment: production

  notify:
    needs: [main-build, release-build]
    runs-on: ubuntu-latest
    steps:
      - name: Notificar Sucesso
        if: success()
        run: echo "Deploy realizado com sucesso para o ambiente ${{ github.ref }}!"

      - name: Notificar Falha
        if: failure()
        run: echo "Deploy falhou para o ambiente ${{ github.ref }}!"

      - name: Sempre Notificar
        if: always()
        run: echo "Pipeline finalizado para o ambiente ${{ github.ref }}."
